#Installing esphome-jk-bms on M5 AtromS3-Light
#https://docs.m5stack.com/en/core/AtomS3%20Lite
#https://www.espressif.com/sites/default/files/documentation/esp32-s3_datasheet_en.pdf

substitutions:
  friendly_name: ESP32-S3 JK PB Inverter BMS
  name: esp32-jk-pb-bms
  device_description: "Monitor and control a JK-BMS via bluetooth"
  external_components_source: github://syssi/esphome-jk-bms@main
  bms0: "${name}-0"
  bms1: "${name}-1"
  bms2: "${name}-2"
  bms3: "${name}-3"
  bms0_mac_address: c8:47:80:11:86:xx
  bms1_mac_address: C8:47:80:10:16:xx
  bms2_mac_address: C8:47:80:0F:F1:xx
  bms3_mac_address: C8:47:80:10:2C:xx
  # Please use "JK02_24S" if you own a old JK-BMS < hardware version 11.0 (hardware version >= 6.0 and < 11.0)
  # Please use "JK02_32S" if you own a new JK-BMS >= hardware version 11.0 (f.e. JK-B2A8S20P hw 11.XW, sw 11.26)
  # Please use "JK04" if you have some old JK-BMS <= hardware version 3.0 (f.e. JK-B2A16S hw 3.0, sw. 3.3.0)
  bms0_protocol_version: JK02_32S
  bms1_protocol_version: JK02_32S
  bms2_protocol_version: JK02_32S
  bms3_protocol_version: JK02_32S

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  comment: ${device_description}
  min_version: 2024.6.0
  project:
    name: "syssi.esphome-jk-bms"
    version: 2.1.0

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf

external_components:
  - source: ${external_components_source}
    refresh: 0s

logger:
  level: DEBUG
  logs:
    esp32_ble_tracker: INFO
    esp32_ble_client: INFO

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

ota:
  platform: esphome
  password: !secret ota_password
  on_begin:
    then:
 #     - switch.turn_off: ble_client_switchx -> included

      - logger.log: "BLE connection suspended for OTA update"

# WLED of S3Light
light:
  # needed for esp-idf: neopixel / fastLED only works with arduino
  # todo: show status / error with color
  - platform: esp32_rmt_led_strip
    rgb_order: GRB
    pin: GPIO35
    num_leds: 1
    # rmt_channel: 0
    chipset: ws2812
    name: "RGB Light"

# User Button of S3Light
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO41
      inverted: true
    name: ${name} Button
    filters:
      - delayed_off: 10ms

esp32_ble_tracker:
  scan_parameters:
    active: false

packages:
# wifi: !include common/wifi.yaml
# https://esphome.io/components/substitutions.html
  wifi: !include
    file: common/wifi.yaml
    vars:
      varFriendlyName: ${friendly_name}
      varName: ${name}

  debug: !include common/debug32.yaml
  common: !include 
    file: common/common.yaml
    vars: 
        varFriendlyName: ${friendly_name}

  multiple_bms_0: !include 
    file: includes/inc_esp32-ble-v14-multiple.yaml
    vars: 
      id: 0
      name: ${bms0}
      bms0_mac_address: ${bms0_mac_address}
      bms0_protocol_version: $s{bms0_protocol_version}

  multiple_bms_1: !include 
    file: includes/inc_esp32-ble-v14-multiple.yaml
    vars: 
      id: 1
      name: ${bms1}
      bms0_mac_address: ${bms1_mac_address}
      bms0_protocol_version: $s{bms1_protocol_version}

  multiple_bms_2: !include 
    file: includes/inc_esp32-ble-v14-multiple.yaml
    vars: 
      id: 2
      name: ${bms2}
      bms0_mac_address: ${bms2_mac_address}
      bms0_protocol_version: $s{bms2_protocol_version}

  multiple_bms_3: !include 
    file: includes/inc_esp32-ble-v14-multiple.yaml
    vars: 
      id: 3
      name: ${bms3}
      bms0_mac_address: ${bms3_mac_address}
      bms0_protocol_version: $s{bms3_protocol_version}
    